### ISSUE TITLE
City influence not expanding if nearby city is destroyed

### ISSUE THREAD

**Issue by LynxAbraxas** [civctp2/civctp2#141]
If a nearby (foreign) city is destroyed a city close by does not expand its region of influence even though it would have a larger region of influence if the former city would not have existed.
This is an unexpected and unlogical behavior. Possibly related to #73?

**Comment by MartinGuehmann** [comment]
No it is not related to #73. It is just that the nearby cities aren't updated. Maybe there is in some code that is supposed to do it, but it may be executed before the city is actually dead or its influence has been removed.

**Comment by LynxAbraxas** [comment]
Solved with #143, which has its own issue for optimization #151.
