### ISSUE TITLE
Introduce bonus for the receiver of a trade route

### ISSUE THREAD

**Issue by LynxAbraxas** [civctp2/civctp2#148]
So far only the civ that sells a good gets something (gold) but not the civ that receives the good. 
Eventhough a message is issued to the receiver if a trade route got cancelled by the sender
https://github.com/civctp2/civctp2/blob/3a375905777f3d902fdbfbe5b2437fb573234555/ctp2_code/gs/gameobj/TradeRoute.cpp#L53-L64
this seems to have no negative effect to the receiver.

Realistic would be that the receiver gets the trade good and pays for that in trun. However the gold that the seller gets
https://github.com/civctp2/civctp2/blob/3a375905777f3d902fdbfbe5b2437fb573234555/ctp2_code/gs/gameobj/CityData.cpp#L4442
is not removed from the receiver.

Types of bonuses the receiver could get:

- gold bonus (which would be illogic, as the receiver should actually have to pay)
- PW/production (coal, iron, oil, glass, ...), food (wheat, rice, crap, fish, mushrooms, banana, dates, ...), happiness (tea, coffe, dye, poppies, chilli, grapes, herbs, sugar, perls, emeralds, elephants, camels), perhaps even some reduce pollution (copper, gold, uran?)
- strategic benefits, like oil to be able to built e.g. tanks

In regard to what could possibly be implemented most easily would probably be to just assign the additional food, production, commerce values of the good received or add the good to the pool of tradable goods.
This way it would be possible to built cities in the mountains or on glaciers where hardly any food is found locally but that could be supplied by trade.

Regarding strategic benefits, we would need to introduce strategic meaning to goods, possibly bound to advances revealing goods, goods being used up after some time (see #142).
All this would also demand that the AI is "taught" to make use of this as well in order to avoid that this only gives benefits to a human player, thereby indirectly weakening the AI.

Any way, some bonus for the receiver would make the trading concept of ctp2 much more interesting.

**Comment by LynxAbraxas** [comment]
@MartinGuehmann any ideas on how to realize "assign the additional food, production, commerce values of the good received"? How much work do you recon that would be?

**Comment by MartinGuehmann** [comment]
> @MartinGuehmann any ideas on how to realize "assign the additional food, production, commerce values of the good received"? How much work do you recon that would be?

I think that is quite easy, the question is just how to do it and what are the boni, would it be the field boni that are then transferred to the other city?

Basically you have to add the stuff when the city collects the food, gold and production.

**Comment by LynxAbraxas** [comment]
> would it be the field boni that are then transferred to the other city?

I guess simplest would be to uses the ones as defined here:
https://github.com/civctp2/civctp2/blob/93ca09d6e24d6b4a8f958da2e16b0a1fdd6af75c/ctp2_data/default/gamedata/goods.txt#L5-L7

**Comment by MartinGuehmann** [comment]
> > would it be the field boni that are then transferred to the other city?
> 
> I guess simplest would be to uses the ones as defined here:
> https://github.com/civctp2/civctp2/blob/93ca09d6e24d6b4a8f958da2e16b0a1fdd6af75c/ctp2_data/default/gamedata/goods.txt#L5-L7

Sure.

**Comment by LynxAbraxas** [comment]
> However the gold that the seller gets is not removed from the receiver.

Apparently that is considered properly here
https://github.com/civctp2/civctp2/blob/20d97537dfca686a8bdad7d2c6e1c69a19f2a3a8/ctp2_code/gs/gameobj/CityData.cpp#L4388-L4397

not sure if that collides with

https://github.com/civctp2/civctp2/blob/3a375905777f3d902fdbfbe5b2437fb573234555/ctp2_code/gs/gameobj/CityData.cpp#L4442

i.e. if `m_goldFromTradeRoutes` is used in the calulations such that the gold is added multiple times.

Some resource assignment seems to be thought of already as well:
https://github.com/civctp2/civctp2/blob/20d97537dfca686a8bdad7d2c6e1c69a19f2a3a8/ctp2_code/gs/gameobj/CityData.cpp#L4405-L4409

**Comment by LynxAbraxas** [comment]
@MartinGuehmann would `NEW_RESOURCE_PROCESS` only be defined here
https://github.com/civctp2/civctp2/blob/20d97537dfca686a8bdad7d2c6e1c69a19f2a3a8/ctp2_code/gs/gameobj/citydata.h#L98
or possibly also somewhere elese? 
Is the game in the current state compiled without the code of `NEW_RESOURCE_PROCESS`?

**Comment by LynxAbraxas** [comment]
It seems the trade resource is added to `m_buyingResources`
https://github.com/civctp2/civctp2/blob/20d97537dfca686a8bdad7d2c6e1c69a19f2a3a8/ctp2_code/gs/gameobj/CityData.cpp#L4275-L4290
but `m_buyingResources` is not considered when resource bonuses are taken into account like goods found inside the city radius
https://github.com/civctp2/civctp2/blob/20d97537dfca686a8bdad7d2c6e1c69a19f2a3a8/ctp2_code/gs/gameobj/CityData.cpp#L2555-L2557
e.g. `GetFoodProduced` leading to
https://github.com/civctp2/civctp2/blob/20d97537dfca686a8bdad7d2c6e1c69a19f2a3a8/ctp2_code/gs/world/Cell.cpp#L335-L338

Goods are added to `m_collectingResources`
https://github.com/civctp2/civctp2/blob/20d97537dfca686a8bdad7d2c6e1c69a19f2a3a8/ctp2_code/gs/gameobj/CityData.cpp#L2560-L2592

**Comment by LynxAbraxas** [comment]
@MartinGuehmann where would be an appropriate place to add additional food, goold and production from bought resources? I.e. where best to take into account `m_buyingResources`?

**Comment by LynxAbraxas** [comment]
@martinguehmann Do you know if this idea
https://github.com/civctp2/civctp2/blob/20d97537dfca686a8bdad7d2c6e1c69a19f2a3a8/ctp2_code/gs/gameobj/CityData.cpp#L7032-L7035
 is actually already in use? There is quite a lot implementation already in the code but I did not have the impression when playing that this is in effect.

**Comment by LynxAbraxas** [comment]
> alize "assign the additional food, production, commerce values of the good received"? How much work do you recon that would be?

#188 tries to implement this.

**Comment by LynxAbraxas** [comment]
Closing this because #188 is now in but feel free to add further ideas on this topic.

**Comment by LynxAbraxas** [comment]
NB: Domestic trade does not give any gold (as one might expect):

https://github.com/civctp2/civctp2/blob/408bbbaae58a7617d546ca6b2fd27b2d1c73eb64/ctp2_code/gs/gameobj/CityData.cpp#L4432-L4444

So before #188, domestic trade effectively was only wasting caravans...
Not sure how domestic trade was taken into account in CTP1, possibly as assumed in https://github.com/civctp2/civctp2/issues/149#issuecomment-526277713.
