### ISSUE TITLE
AI logic for trade route creation/removal seems bad

### ISSUE THREAD

**Issue by LynxAbraxas** [civctp2/civctp2#155]
When giving the human-player to the AI for one turn, the AI gives up trade routes and establishes new ones but in total with a far lower profit.
13 trade routes with a total profit of 941 before letting the AI play for one turn (`/attach 1`):

![ss_2019-06-23_18:28:02](https://user-images.githubusercontent.com/21012234/59979223-0aa2c680-95e5-11e9-8865-757f98d5562d.png)

afterwards 5 routes with a total of only 340:

![ss_2019-06-23_18:02:41](https://user-images.githubusercontent.com/21012234/59979142-0924ce80-95e4-11e9-8090-3496a7dc9ee1.png)

**Comment by MartinGuehmann** [comment]
As far as I could see the AI also only considers a limited number of trade routes. And it cannot really make up its mind.

**Comment by LynxAbraxas** [comment]
This code is likely related
https://github.com/civctp2/civctp2/blob/82a15c92ee2b85adf01e56f89e334a15e8926dbb/ctp2_code/ai/CityManagement/governor.cpp#L5174-L5212

**Comment by LynxAbraxas** [comment]
Canceling trade routes that are pirated more often than
https://github.com/civctp2/civctp2/blob/2c9b619e1bb4fe4e3fab1b86dddf521482e930d7/ctp2_data/default/aidata/strategies.txt#L503-L504
are degraded by
https://github.com/civctp2/civctp2/blob/2c9b619e1bb4fe4e3fab1b86dddf521482e930d7/ctp2_code/ai/diplomacy/diplomat.cpp#L4441-L4473
which is used for deciding here
https://github.com/civctp2/civctp2/blob/82a15c92ee2b85adf01e56f89e334a15e8926dbb/ctp2_code/ai/CityManagement/governor.cpp#L5158-L5172

**Comment by LynxAbraxas** [comment]
Just another evidence that the trade routes created by the AI are very inefficient (ratio of caravans to profit is low).

Only one route for 38 gold that needs 12 caravans:
![ss_2019-12-01_16:45:56](https://user-images.githubusercontent.com/21012234/69916463-8be76a80-145b-11ea-9c56-88ff7fce1e16.png)

whereas there are offers of e.g. 88 gold for just 5 caravans by the same civ (Irish), and the treasury is very low:
![ss_2019-12-01_16:58:16](https://user-images.githubusercontent.com/21012234/69916490-de288b80-145b-11ea-952a-c0e6da370918.png)

**Comment by LynxAbraxas** [comment]
With #188, it would be great if the trade route creation/validation algorithm would take into account:
- bonus gained from the trade
- ratio of cost and number of caravans
- include domestic trade considerations for the AI (e.g. food support (by bonus) for its weak cities)

**Comment by LynxAbraxas** [comment]
> As far as I could see the AI also only considers a limited number of trade routes. And it cannot really make up its mind.

@MartinGuehmann Where did you see that?

**Comment by MartinGuehmann** [comment]
That's just a subjective observation from my test games. The AI does not have that many trade routes and it breaks them and makes new routes. Basically, the behavior you are addressing in you pull requests.

**Comment by LynxAbraxas** [comment]
> That's just a subjective observation from my test games. 

I see.

> The AI does not have that many trade routes 

Probably the bug addressed in #252

>  and makes new routes

Probably due to not considering that a caravan is lost when cancelling a route.

**Comment by MartinGuehmann** [comment]
Interesting, this is linked to #252, and thus was closed when I merged that pull request.
