### ISSUE TITLE
City-Icon for conversion, franchies etc should update even for cities in fog-of-war

### ISSUE THREAD

**Issue by LynxAbraxas** [civctp2/civctp2#158]
Currently, at least with SDL, the icon of a city indicating conversion or franchise does not update if the city is in fog-of-war. However, since in any case some kind of income occurs per round, such an icon should vanish (for the receiving civ) if the conversion or franchise is removed even if that city is in fog-of-war as the income does not occur any more.

**Comment by MartinGuehmann** [comment]
Actually, if you want to update the icon, even in fog of war then you should also send a message to the franchise owner if the franchise is cleared.

**Comment by LynxAbraxas** [comment]
I though of trying to do less message spamming and just removing the icon. Any idea for where to start?

**Comment by LynxAbraxas** [comment]
This can be closed since #166 is merged and #171 is on the way.
