### ISSUE TITLE
AI apparently neither doing Franchise attacks nor Suing Franchises in its cities

### ISSUE THREAD

**Issue by LynxAbraxas** [civctp2/civctp2#169]
Apparently the AI neither does Franchise attacks nor Suing Franchises in its cities, see also https://github.com/civctp2/civctp2/pull/167#issuecomment-512394317.

**Comment by LynxAbraxas** [comment]
Possibly something wrong around here:
https://github.com/civctp2/civctp2/blob/4bb84c20542f4d9d85199c445cffb75b96cd627b/ctp2_code/ai/strategy/goals/Goal.cpp#L2878-L2882

**Comment by LynxAbraxas** [comment]
@MartinGuehmann any idea how to make this possible?

**Comment by LynxAbraxas** [comment]
Concerning the establishing of Franchises:
@MartinGuehmann shouldn't this test
https://github.com/civctp2/civctp2/blob/2c9b619e1bb4fe4e3fab1b86dddf521482e930d7/ctp2_code/ai/strategy/goals/Goal.cpp#L2890-L2894
be based on the franchise owner being `>= 0` instead of `FranchiseTurnsRemaining`?

**Comment by LynxAbraxas** [comment]
Concerning suing of Franchises:
This seems fine
https://github.com/civctp2/civctp2/blob/2c9b619e1bb4fe4e3fab1b86dddf521482e930d7/ctp2_code/ai/strategy/goals/Goal.cpp#L2878-L2882
but might be without effect due to
https://github.com/civctp2/civctp2/blob/82a15c92ee2b85adf01e56f89e334a15e8926dbb/ctp2_code/gs/gameobj/Unit.cpp#L2422-L2423
which probably is due to the fact that a `CanSueFranchise` apparently is not implemented.

**Comment by LynxAbraxas** [comment]
Before 76f7820eb764077640cdf2eeaed6d9dd32894ba3 there was
https://github.com/civctp2/civctp2/blob/1fa7e961cb47c3012c64f6ec443e3eb779aebaf6/ctp2_code/robotcom/Agent/armyagent.cpp#L2316-L2336

**Comment by LynxAbraxas** [comment]
@MartinGuehmann these lines
https://github.com/civctp2/civctp2/blob/82a15c92ee2b85adf01e56f89e334a15e8926dbb/ctp2_code/gs/gameobj/Unit.cpp#L2422-L2423
seem to appear in e500b666413db49f981a19bbd541e06a86396b8a, any chance you remember where those originated from?

**Comment by MartinGuehmann** [comment]
> @MartinGuehmann these lines
> https://github.com/civctp2/civctp2/blob/82a15c92ee2b85adf01e56f89e334a15e8926dbb/ctp2_code/gs/gameobj/Unit.cpp#L2422-L2423
> 
> 
> seem to appear in [e500b66](https://github.com/civctp2/civctp2/commit/e500b666413db49f981a19bbd541e06a86396b8a), any chance you remember where those originated from?

Looking at that stuff, I moved the function UnitValidForOrder from ArmyData to Unit, so that I could implement the government modified thing. Probably when I did I added the out commented lines. Probably as a reminder, but I never followed up on these. Obviously, as a player I would only create franchises, and I wouldn't care if the AI does not clear them.

Probably this is why I did not finish it:

> which probably is due to the fact that a CanSueFranchise apparently is not implemented.

But looking at the database, I would say that CanSue should cover it. So that should be an easy fix. So actually this means you could never sue franchises in CTP2.

**Comment by MartinGuehmann** [comment]
> Before [76f7820](https://github.com/civctp2/civctp2/commit/76f7820eb764077640cdf2eeaed6d9dd32894ba3) there was
> https://github.com/civctp2/civctp2/blob/1fa7e961cb47c3012c64f6ec443e3eb779aebaf6/ctp2_code/robotcom/Agent/armyagent.cpp#L2316-L2336

Here, I removed quite some stuff. All these files were not used anyway. In fact these files just distract if you wanna understand the code, and they were also included in one or two files, which blew also up the file size of the executable.

**Comment by MartinGuehmann** [comment]
> Concerning the establishing of Franchises:
> @MartinGuehmann shouldn't this test
> https://github.com/civctp2/civctp2/blob/2c9b619e1bb4fe4e3fab1b86dddf521482e930d7/ctp2_code/ai/strategy/goals/Goal.cpp#L2890-L2894
> 
> 
> be based on the franchise owner being `>= 0` instead of `FranchiseTurnsRemaining`?

Sure, this should be based on the franchise owner. Of course, we could think about some alternatives, like that you can replace a foreign franchise with your own. Or renew it if has a limited number of turns. But actually, I would prefer that you can only establish a new franchise if the city is clear, otherwise things get too complicated.

**Comment by LynxAbraxas** [comment]
> But looking at the database, I would say that CanSue should cover it. So that should be an easy fix. 

Many thanks for that hint. 

> So actually this means you could never sue franchises in CTP2.

Well the AI never could (so far) and a player could not until https://github.com/civctp2/civctp2/pull/167/commits/be207ac79f9237560226ccd5628be6a3b2835bb3 of #167.

**Comment by LynxAbraxas** [comment]
> Sure, this should be based on the franchise owner. Of course, we could think about some alternatives, like that you can replace a foreign franchise with your own. Or renew it if has a limited number of turns. But actually, I would prefer that you can only establish a new franchise if the city is clear, otherwise things get too complicated.

Currently testing with https://github.com/civctp2/civctp2/pull/176/commits/978ace19879b65a01cf619a2e609d81ac0e6e50e of #176 if doing it the same as is done for conversions works.

**Comment by MartinGuehmann** [comment]
> > So actually this means you could never sue franchises in CTP2.
> 
> Well the AI never could (so far) and a player could not until [be207ac](https://github.com/civctp2/civctp2/commit/be207ac79f9237560226ccd5628be6a3b2835bb3) of #167.

Yeah, it is a bit irritating, basically the human player uses the sue order to sue enemy units and franchises, however for the AI these are two orders.

**Comment by LynxAbraxas** [comment]
@MartinGuehmann  How would you recommend to test such changes? Any more direct way than a game on "auto run"?

**Comment by MartinGuehmann** [comment]
> @MartinGuehmann How would you recommend to test such changes? Any more direct way than a game on "auto run"?

Well, you need the debug logs, you get them either with a debug version or with the final version with logging. I am not hundred percent sure, whether I tested the logging only version on Linux, bet well you have to read the logs and see whether the AI plans with the Lawyers and Corporate Branches these attacks and the suing.

You have to search for the goals in the logs, for instance GOAL_FRANCHISING. Over time we added quite a lot to the debugging logs. I also polished them this year. For instance, there is somewhere a summary table of how many goals of each type the AI considers.

**Comment by LynxAbraxas** [comment]
Just noticed a subtle difference, while it is e.g.
`GetUnitPretest_CanSue` and `GetCanSue` 
`GetUnitPretest_CanCreateFranchise` and `GetCreateFranchise` and not `GetCanCreateFranchise`
https://github.com/civctp2/civctp2/blob/82a15c92ee2b85adf01e56f89e334a15e8926dbb/ctp2_code/gs/gameobj/Unit.cpp#L2422-L2427
@MartinGuehmann does that matter? 
Should it be `GetCanSueFranchise` or `GetSueFranchise`?

**Comment by LynxAbraxas** [comment]
NB: There is no `GetUnitPretest_CanSue()` in 
https://github.com/civctp2/civctp2/blob/2c9b619e1bb4fe4e3fab1b86dddf521482e930d7/ctp2_code/ai/strategy/goals/Goal.cpp#L2717-L2976
or anywhere else in `Goal.cpp`. 
@MartinGuehmann is that a bug or intentionally not contained?

**Comment by MartinGuehmann** [comment]
> NB: There is no `GetUnitPretest_CanSue()` in
> https://github.com/civctp2/civctp2/blob/2c9b619e1bb4fe4e3fab1b86dddf521482e930d7/ctp2_code/ai/strategy/goals/Goal.cpp#L2717-L2976
> 
> 
> or anywhere else in `Goal.cpp`.
> @MartinGuehmann is that a bug or intentionally not contained?

I would call it a bug. What it means is that the AI would try to sue any unit even so the unit cannot be sued.

Basically, it should be something like as it is done with GetUnitPretest_CanEnslaveSettler().

**Comment by MartinGuehmann** [comment]
> @MartinGuehmann what maps `CanCreateFranchise` to `CreateFranchise` or vice versa?
> In regard to #176, should it be `GetCanSueFranchise` or `GetSueFranchise`?

Well, again Activision doesn't seem to have a convention how to call these things. So one is defined in ArmyData and the other in UnitRecord, which is generated from unit.cdb. So, I would just search ArmyData.h for functions containing Franchise and check them whether they do the right thing. And if I don't find such a function just create one.

**Comment by LynxAbraxas** [comment]
> > @MartinGuehmann what maps `CanCreateFranchise` to `CreateFranchise` or vice versa?
> > In regard to #176, should it be `GetCanSueFranchise` or `GetSueFranchise`?
> 
> Well, again Activision doesn't seem to have a convention how to call these things. So one is defined in ArmyData and the other in UnitRecord, which is generated from unit.cdb. So, I would just search ArmyData.h for functions containing Franchise and check them whether they do the right thing. And if I don't find such a function just create one.

I think I was looking for this
https://github.com/civctp2/civctp2/blob/82a15c92ee2b85adf01e56f89e334a15e8926dbb/ctp2_code/gs/gameobj/Order.cpp#L258-L279
or this
https://github.com/civctp2/civctp2/blob/82a15c92ee2b85adf01e56f89e334a15e8926dbb/ctp2_code/gs/gameobj/ArmyData.cpp#L10915-L10934
which would map
https://github.com/civctp2/civctp2/blob/82a15c92ee2b85adf01e56f89e334a15e8926dbb/ctp2_data/default/gamedata/Units.txt#L993-L997
over
https://github.com/civctp2/civctp2/blob/82a15c92ee2b85adf01e56f89e334a15e8926dbb/ctp2_code/gs/gameobj/armyevent.cpp#L358-L367
to
https://github.com/civctp2/civctp2/blob/82a15c92ee2b85adf01e56f89e334a15e8926dbb/ctp2_code/gs/gameobj/ArmyData.cpp#L2157-L2206

**Comment by LynxAbraxas** [comment]
Solved with #176.
