### ISSUE TITLE
Nanite cleansing leads to "No such object" error

### ISSUE THREAD

**Issue by LynxAbraxas** [civctp2/civctp2#226]
Nanite cleansing leads to "No such object" 
![ss_2019-12-27_22:02:03](https://user-images.githubusercontent.com/21012234/71533459-0ee3cf80-28f9-11ea-919e-7c342f169800.png)
from
https://github.com/civctp2/civctp2/blob/bf9a81223e9c1ec266364807555fe9ffc7b75b60/ctp2_code/gs/gameobj/GameObj.cpp#L92-L93
Same happens for `/gw` easter-egg. So I would guess it originates from the removal of a city/unit.

**Comment by LynxAbraxas** [comment]
Oddly, this does not happen for the debug version of the game, even if compiled with `-O3`, so apparently this is not connected to optimization but to the debug directive.
@MartinGuehmann any idea what could cause this in the plain version?

**Comment by MartinGuehmann** [comment]
> Oddly, this does not happen for the debug version of the game, even if compiled with `-O3`, so apparently this is not connected to optimization but to the debug directive.
> @MartinGuehmann any idea what could cause this in the plain version?

I don't know, I had no problem when I tried these things last time. But there I cannot remember whether that was the debug version or not.

**Comment by LynxAbraxas** [comment]
Probably caused by fe3b57cd409a00acef78855208219a5e7362cb86 from #195:

```
Thread 1 "ctp2" received signal SIGSEGV, Segmentation fault.
0x00005555557902ba in UnitData::GetOwner() const ()
(gdb) bt
#0  0x00005555557902ba in UnitData::GetOwner() const ()
#1  0x00005555560917d4 in Unit::GetOwner() const ()
#2  0x000055555608c8b0 in TradeRoute::RemoveAllReferences(CAUSE_KILL_TRADE_ROUTE) ()
#3  0x000055555608c658 in TradeRoute::KillRoute(CAUSE_KILL_TRADE_ROUTE) ()
#4  0x000055555578fe8e in TradeRoute::Kill(CAUSE_KILL_TRADE_ROUTE) ()
#5  0x000055555600931e in CityData::~CityData() ()
#6  0x0000555556009504 in CityData::~CityData() ()
#7  0x00005555560985b8 in UnitData::~UnitData() ()
#8  0x000055555609869c in UnitData::~UnitData() ()
#9  0x0000555556043a05 in GameObj_Delete(GameObj**, unsigned int) ()
#10 0x0000555556052891 in ObjPool::Del(ID const&) ()
#11 0x00005555560912ee in Unit::RemoveAllReferences(CAUSE_REMOVE_ARMY, int) ()
#12 0x0000555556090ae2 in Unit::KillUnit(CAUSE_REMOVE_ARMY, int) ()
#13 0x00005555558bcfd4 in Unit::Kill(CAUSE_REMOVE_ARMY, int) ()
#14 0x00005555560179fc in CityData::CityToPark(int) ()
#15 0x00005555560a0dd2 in UnitData::CityToPark(int) ()
#16 0x000055555609446f in Unit::CityToPark(int) ()
#17 0x00005555560c6171 in CreateParkEvent::GEVHookCallback(GAME_EVENT, GameEventArgList*) ()
#18 0x0000555555fc0500 in GameEventHook::Activate(GameEventArgList*, int, int&) const ()
#19 0x0000555555fbd9c4 in GameEventManager::ActivateHook(GAME_EVENT, GameEventArgList*, int, int&) ()
#20 0x0000555555fbff27 in GameEvent::Process() ()
#21 0x0000555555fbd6b4 in GameEventManager::ProcessHead() ()
#22 0x0000555555fbd5e3 in GameEventManager::Process() ()
#23 0x0000555555780f4b in CivApp::Process() ()
#24 0x0000555555776cec in CivMain(int, char**) ()
#25 0x0000555555776889 in main ()
```

**Comment by MartinGuehmann** [comment]
> Probably caused by [fe3b57c](https://github.com/civctp2/civctp2/commit/fe3b57cd409a00acef78855208219a5e7362cb86) from #195:

Did you try if you undo you change, would the problem go?

I find it a bit odd. In fact source and dest are checked for being valid. Which seem to be valid. Then the code you have outcommented should already trigger the problem.

It might be a problem that was already there but wasn't noticed for some reason. It could be something to with the fact that the objects you are accessing are being deleted.

**Comment by LynxAbraxas** [comment]
Figured it was actually caused by https://github.com/civctp2/civctp2/pull/195/commits/8f5b943609cb8d8f2e851cdf488837bdb9b7346a, problem gone with reverting that (https://github.com/civctp2/civctp2/pull/195/commits/4d57a2684a52c49d9ebbe672a1e8011b764e86a3).
