### ISSUE TITLE
Launched space plane newer seems to reach target

### ISSUE THREAD

**Issue by LynxAbraxas** [civctp2/civctp2#229]
It seems that units loaded into a space plane and launched never reach their destination, at least not even after more than 20 turns, neither for land nor water cities.
Space lifts would become interesting for far-off cities created for building obelisks for the science victory.

**Comment by MartinGuehmann** [comment]
Space lifts only work between existing cities, so why would they be interesting? You can already build obelisks in cities you own, even so they are on the other side of the world.

**Comment by LynxAbraxas** [comment]
> Space lifts only work between existing cities

That's what I was expecting and found not to work.

> so why would they be interesting? You can already build obelisks in cities you own, even so they are on the other side of the world.

Yes, but those cities might need a garrison which in some cases could be provided faster with a space lift than by other means.
While I tested the space lift between land (and water) cities, it would be most interesting if it also worked for sea colonies.

**Comment by LynxAbraxas** [comment]
I now had my very first successful space transport, will test this further.

**Comment by LynxAbraxas** [comment]
It seems `m_reentryTurn` and `m_reentryPos` are not saved, so the problem arises if a space plane is in space when a game is saved and reloaded. Then

https://github.com/civctp2/civctp2/blob/11b9a024f4e0b5ace7011f6e53a49f5f7bb83651/ctp2_code/gs/gameobj/ArmyData.cpp#L1735
is true because `m_reentryTurn` is initialized to `-1` which leads to
https://github.com/civctp2/civctp2/blob/11b9a024f4e0b5ace7011f6e53a49f5f7bb83651/ctp2_code/gs/gameobj/ArmyData.cpp#L4685-L4696
where the not stored `m_reentryPos` leads to an invalid city and the destruction of the space plane and its units.
So to solve this, where do we have some unused space in the current save game format where `m_reentryTurn` and `m_reentryPos` could be saved? @MartinGuehmann any ideas?

**Comment by LynxAbraxas** [comment]
Solved with #321.
