### ISSUE TITLE
Trade pact bonus not considered

### ISSUE THREAD

**Issue by LynxAbraxas** [civctp2/civctp2#234]
It seems like the trade pact bonus is not considered, or it is so low that it does not make a noticeable difference.

**Comment by LynxAbraxas** [comment]
It is very low (and hard-coded):
https://github.com/civctp2/civctp2/blob/ea3274c3d43176670ac71f6bc75703fac18a226e/ctp2_code/gs/gameobj/tradeutil.cpp#L66-L73

**Comment by MartinGuehmann** [comment]
And of course, E is right here. It should go to const.txt

**Comment by LynxAbraxas** [comment]
Hm, actually, the value from `tradeutil_GetTradeValue` is not used here:
https://github.com/civctp2/civctp2/blob/ea3274c3d43176670ac71f6bc75703fac18a226e/ctp2_code/gs/gameobj/TradeRouteData.cpp#L591-L599
so the bonus is not taken into account later, e.g. in the trade manger listing:
https://github.com/civctp2/civctp2/blob/ea3274c3d43176670ac71f6bc75703fac18a226e/ctp2_code/ui/interface/trademanager.cpp#L744-L753
and I have the impression, that no gold is passed from the receiver to the sender here
https://github.com/civctp2/civctp2/blob/ea3274c3d43176670ac71f6bc75703fac18a226e/ctp2_code/gs/gameobj/CityData.cpp#L4462-L4471
because `GetGoldInReturn` is 0
https://github.com/civctp2/civctp2/blob/ea3274c3d43176670ac71f6bc75703fac18a226e/ctp2_code/gs/gameobj/PlayerEvent.cpp#L556-L558
and otherwise apparently not related to `GetValue` which would mean that no actual gold is earned from trade routes at all.
@MartinGuehmann any idea what is meant to be the difference between `GetGoldInReturn` and `GetValue`? Is `GetGoldInReturn` a remainder from CTP1 trade bids?

**Comment by LynxAbraxas** [comment]
@MartinGuehmann Any idea why it apparently does not matter here whether `->` is used
https://github.com/civctp2/civctp2/blob/ea3274c3d43176670ac71f6bc75703fac18a226e/ctp2_code/ui/interface/trademanager.cpp#L745
or `.`
https://github.com/civctp2/civctp2/blob/ea3274c3d43176670ac71f6bc75703fac18a226e/ctp2_code/ui/interface/trademanager.cpp#L758
`route` is an instance
https://github.com/civctp2/civctp2/blob/ea3274c3d43176670ac71f6bc75703fac18a226e/ctp2_code/ui/interface/trademanager.cpp#L683
so I would expect that it has to be `->` in both cases, however the code seems to work all right as is.

**Comment by LynxAbraxas** [comment]
> and I have the impression, that no gold is passed from the receiver to the sender here
> 
> https://github.com/civctp2/civctp2/blob/ea3274c3d43176670ac71f6bc75703fac18a226e/ctp2_code/gs/gameobj/CityData.cpp#L4462-L4471
> 
> because `GetGoldInReturn` is 0

But it is given to the sender here (pact bonus also not taken into account)
https://github.com/civctp2/civctp2/blob/ea3274c3d43176670ac71f6bc75703fac18a226e/ctp2_code/gs/gameobj/CityData.cpp#L4510-L4538
but apparently it is not removed from the receiver.

**Comment by MartinGuehmann** [comment]
> @MartinGuehmann Any idea why it apparently does not matter here whether `->` is used
> https://github.com/civctp2/civctp2/blob/ea3274c3d43176670ac71f6bc75703fac18a226e/ctp2_code/ui/interface/trademanager.cpp#L745
> 
> 
> or `.`
> https://github.com/civctp2/civctp2/blob/ea3274c3d43176670ac71f6bc75703fac18a226e/ctp2_code/ui/interface/trademanager.cpp#L758
> 
> 
> `route` is an instance
> https://github.com/civctp2/civctp2/blob/ea3274c3d43176670ac71f6bc75703fac18a226e/ctp2_code/ui/interface/trademanager.cpp#L683
> 
> 
> so I would expect that it has to be `->` in both cases, however the code seems to work all right as is.

That's because the TradeRoute class has a '->' operator, which accesses the TradeRouteData object. And it also implements also implements methods that access the according function of the TradeRouteData object. The difference is that the '.' works on const objects only.

**Comment by LynxAbraxas** [comment]
Thanks for that explanation, never saw that before. Do you know if this has a name that I could google for more common examples of this?

**Comment by MartinGuehmann** [comment]
Well, you also have such a thing for Army and Unit. The concept is called operator overloading. Here is the first thing I found:

https://en.cppreference.com/w/cpp/language/operators

I would say this is quite standard c++, you could just wonder whether it is logical to implement the '->' in this way, but that's the way Activision went for.

**Comment by LynxAbraxas** [comment]
> I would say this is quite standard c++, you could just wonder whether it is logical to implement the '->' in this way, but that's the way Activision went for.

Yes, that's what was new to me. So far I had only seen operator overloads for e.g. `<<` or `<` like here:
https://github.com/civctp2/civctp2/blob/ea3274c3d43176670ac71f6bc75703fac18a226e/ctp2_code/ai/CityManagement/governor.cpp#L5036-L5045
but never one for `->` mimicking the `.`.

**Comment by LynxAbraxas** [comment]
I just learned that the `->` ("member of pointer ") operator can be overloaded but the  `.` ("member of object") operator not: https://en.cppreference.com/w/cpp/language/operator_member_access

And here it is done for `TradeRouteData`:
https://github.com/civctp2/civctp2/blob/ea3274c3d43176670ac71f6bc75703fac18a226e/ctp2_code/gs/gameobj/TradeRoute.h#L47

**Comment by LynxAbraxas** [comment]
OK with f951d2fc8ca0b31a6778cd3f207ab3e952052a78 it is (https://github.com/civctp2/civctp2/pull/252#issuecomment-579926639), so just using the ConstDB is left.

**Comment by LynxAbraxas** [comment]
> so just using the ConstDB is left.

Done in 7f5b6880aca0051e432fadb873e6dfddde6ac47a of #255.
