### ISSUE TITLE
"Submarine Canyon" tiles not working (appearing in maps)

### ISSUE THREAD

**Issue by LynxAbraxas** [civctp2/civctp2#248]
It seems that currently the map cannot have "Submarine Canyon" tiles. When I try to insert them, only deep water is put there:
![ss_2020-01-16_10:08:23](https://user-images.githubusercontent.com/21012234/72518252-31f90380-3855-11ea-8dad-57fee9e1344f.png)

**Comment by LynxAbraxas** [comment]
Are "Submarine Canyon" tiles the correspondent of "Trench" tiles in CTP1?
![ss_2020-01-12_19:16:43](https://user-images.githubusercontent.com/21012234/72518344-68cf1980-3855-11ea-865e-bcb9917c13a2.png)

**Comment by LynxAbraxas** [comment]
I have found some submarine canyon tiles on a CTP2 map now, but some forms look as if they come form the CPT1 tile set:
![ss_2020-01-30_16:40:30](https://user-images.githubusercontent.com/21012234/73467100-1cbac380-4383-11ea-96bc-9264c1b048a8.png)
Drawing these with the map editor still does not work for me.

**Comment by LynxAbraxas** [comment]
"Submarine Canyon" (trench) tiles were disabled for map generation in:  8b2beddb5d3497aef2deb2142fee7601764de904

Apparently CTP2 trench tiles are in [gtset565.til](https://github.com/civctp2/civctp2/blob/e1750a0a6e4e4d92ea475d447d6d766841fb72f8/ctp2_data/default/graphics/tiles/gtset565.til) but incomplete (27ef00e36d3c01ec1e9c6ea6bd6c9835a33c6436), possibly could be created and added with "TileEdit" (#185).

**Comment by MartinGuehmann** [comment]
I assume that you have to just adjust the color of the CTP2 trench tiles and then you are fine.

**Comment by LynxAbraxas** [comment]
> I assume that you have to just adjust the color of the CTP2 trench tiles and then you are fine.

Done in #353.

**Comment by LynxAbraxas** [comment]
Solved with #353.
