### ISSUE TITLE
Error when loading AE Mod Scenario

### ISSUE THREAD

**Issue by madand** [civctp2/civctp2#284]
![Screenshot_20200322_174941](https://user-images.githubusercontent.com/2280844/77253821-a725f200-6c65-11ea-9000-fdceac07675a.png)

I guess @LynxAbraxas forgot to introduce some changes from his `ctp2CD` directory into this repository.

**Comment by LynxAbraxas** [comment]
Seems I forgot the `Const.txt` from the Scenarios in 398f3a29cf555053ea9ba16c6b6a253bc68d8151. Just adding
```
TURNS_FRANCHISED        -1      # How many turns a franchise will be effective, -1: infinit
```
or similar should do the trick.

**Comment by MartinGuehmann** [comment]
Well, @LynxAbraxas, you could have just added a default value for the new flag, then you don't need to edit any const.txts from scenarios or mods.

**Comment by LynxAbraxas** [comment]
I'll check, not sure where I missed that.

**Comment by MartinGuehmann** [comment]
It's in Const.cdb, just scroll to the bottom of that lengthy list to see how it is done.

**Comment by LynxAbraxas** [comment]
I see, kind of obvious, not sure why I have missed that then, sorry for that. #286 contains a fix.
