### ISSUE TITLE
GL-CI integration for civctp2 is gone

### ISSUE THREAD

**Issue by LynxAbraxas** [civctp2/civctp2#285]
It seems on 2020-03-22 GL stopped the possibility to integrate GH into private repos:
https://about.gitlab.com/releases/2020/03/12/free-period-for-cicd-external-repositories/
While civctp2 in general is open/public, the very special licenses of the source code of CTP2 does not allow us to make the GL fork public because we cannot keep the docker registry private, since the docker images hold the files form the CD and these are needed for the integrated testing.

**Comment by LynxAbraxas** [comment]
GL reverted this for now:
https://gitlab.com/gitlab-org/gitlab/-/issues/10361#note_309549475

**Comment by LynxAbraxas** [comment]
Back to disabled without a paid plan: https://gitlab.com/gitlab-org/gitlab/-/issues/10361#note_312582813
I made a post for the alternative configuration (https://gitlab.com/gitlab-org/gitlab/issues/19585#note_311301489), that only the registry is kept private, which would be nicer any way since compile logs then would be public and available for  discussion directly. 
Until that is available, @MartinGuehmann would have to push to the GL repo after a merge on GH for the smoke tests to run because it is not just the integration with GH that is gone but also the option to activate pull for mirroring in private GL repos. 
Perhaps GH has an option to do push mirroring on merges, which could be an alternative.

**Comment by LynxAbraxas** [comment]
With https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54831 in GL-14.x (GL-14.2 is running on gitlab.com now), the DI registry can be kept private while making the project public.
So with that settings, pulling from GH works again (might need to be reactivated on GL because the pull-mirroring is disabled after 14 failures: https://docs.gitlab.com/ee/user/project/repository/repository_mirroring.html#how-it-works).
Furthermore, GL-CI/CD minutes are not limited any more (https://docs.gitlab.com/ee/subscriptions/gitlab_com/index.html#ci-pipeline-minutes) since it is a public project created before 2021-07-17.

**Comment by LynxAbraxas** [comment]
@MartinGuehmann Can you change those settings for https://gitlab.com/civctp2/civctp2 ?
1. under Settings > General > Project visibility > choos public  and set "Container registry" to "Only Project Members"
2. under Settings > Repository -> Mirroring repositoriesRepository try to update the pull-mirroring, if that is stuck on updating, it needs to be deleted and added (https://docs.gitlab.com/ee/user/project/repository/repository_mirroring.html#pull-from-a-remote-repository)

New PRs should then again get synced from GH to GL and tested by GL-CI, similar to e.g. https://gitlab.com/LynxAbraxas/civctp2/-/pipelines, even the screenshots from the smoke tests are then available as artifacts (https://gitlab.com/LynxAbraxas/civctp2/-/jobs/1476253329/artifacts/file/play-game_build-city.png) and the GL-CI results will become visible on GH (https://github.com/LynxAbraxas/civctp2/branches).

**Comment by LynxAbraxas** [comment]
> @MartinGuehmann Can you change those settings for https://gitlab.com/civctp2/civctp2 ?
> 
>     1. under Settings > General > Project visibility > choos public  and set "Container registry" to "Only Project Members"
> 
>     2. under Settings > Repository -> Mirroring repositoriesRepository try to update the pull-mirroring, if that is stuck on updating, it needs to be deleted and added (https://docs.gitlab.com/ee/user/project/repository/repository_mirroring.html#pull-from-a-remote-repository)
> 
> 
> New PRs should then again get synced from GH to GL and tested by GL-CI, similar to e.g. https://gitlab.com/LynxAbraxas/civctp2/-/pipelines, even the screenshots from the smoke tests are then available as artifacts (https://gitlab.com/LynxAbraxas/civctp2/-/jobs/1476253329/artifacts/file/play-game_build-city.png) and the GL-CI results will become visible on GH (https://github.com/LynxAbraxas/civctp2/branches).



@MartinGuehmann Did You have any chance to test the new settings for civctp2 on GL?

**Comment by MartinGuehmann** [comment]
I updated the settings and the test for the last merge passed:
Merge pull request #367 from williamd67/unit-control-panel-improvements

I also noticed that Travis doesn't check is that related?

**Comment by LynxAbraxas** [comment]
> I updated the settings and the test for the last merge passed: Merge pull request #367 from williamd67/unit-control-panel-improvements

That's great! Many thanks!
For those who wonder what is meant, the test pipeline status can be seen here (again):
https://gitlab.com/civctp2/civctp2/-/pipelines

> I also noticed that Travis doesn't check is that related?

Probably not, though I'm no expert for Travis.

**Comment by MartinGuehmann** [comment]
At least, the pipeline will tell us that it compiles.

**Comment by LynxAbraxas** [comment]
> At least, the pipeline will tell us that it compiles.

On my GH fork the test-status of each branch is taken from the GL-CI/CD tests (at least since it works again), can't remember though if I had to configure that or if it worked out of the box, it might be some of the GH integration settings on GL or the other way round.

**Comment by LynxAbraxas** [comment]
The screen shots of the tests are also now available, e.g.:
https://gitlab.com/civctp2/civctp2/-/jobs/1923289708/artifacts/file/play-game_build-city.png

**Comment by LynxAbraxas** [comment]
@MartinGuehmann this might do it:
https://docs.gitlab.com/ee/ci/ci_cd_for_external_repos/github_integration.html#connect-manually
