### ISSUE TITLE
map acquired in exchange with another player does not show

### ISSUE THREAD

**Issue by LynxAbraxas** [civctp2/civctp2#29]
When requesting a map in exchange from another player in a *diplomatic proposal* and the proposal is accepted, the region of the new map part is not show, i.e. fog of war stays the same (master branch run under linux). This is likely an SDL/linux-port bug and not present in the windows version.

**Comment by LynxAbraxas** [comment]
Seems to be solved with #35, but even with #36 the *diplomatic proposal* window closes after clicking *Send* without waiting for a click on *OK* if the *diplomatic proposal* was initiated by an AI player. The agreement seem to be effective though. In a way the *OK* button only seems to serve as a "close window" button while the actual processing of agreements already happens when *Send* is clicked, still I find this behavior a bit irritating.

**Comment by MartinGuehmann** [comment]
Since, #35 and #36 have been merged into master, I guess this cane be closed. Unless there is something else.

**Comment by LynxAbraxas** [comment]
Yes, did some testing and #35 already resolves this. The closing after clicking *Send* is probably also under windows (@MartinGuehmann is it?) but does not seem to have any influence on the validity of the game state.
