### ISSUE TITLE
Save-directories not automatically created

### ISSUE THREAD

**Issue by williamd67** [civctp2/civctp2#290]
I built (Ubuntu 18.04; gcc-7.50; g++ 7.50) the source-code and first encountered the same issues as madand #269 with incorrect GoG-data. After reading the thread I was able to start the game but still got assertions on save-directories. I found two things:
1. _fullpath is functional (not returning NULL) on Windows even if the last part does not exist, while on Linux (canonicalize_file_name) returns NULL when the last part does not exist; this causes some assertions to fire (I read in another thread that one was already silenced); I propose to update the GNU-specific implementation of _fullname so that it in case of initial failure, the dirname of the path is tested in stead of the whole path
2. CivPaths::CreateSaveFolders does not create the subfolders; this is caused by the fact that path is given to the c3files_CreateDirectory method in stead of subFolderPath

I have a fix for both. Please let me know if you want me to create a pull-request for it.

BTW: I like civilization games in general and really appreciate all your work.

**Comment by MartinGuehmann** [comment]
Why do you think that you must ask to create a pull request? It's not how it should behave and thus should be fixed.

**Comment by LynxAbraxas** [comment]
Sure, with a PR it is the most precise way to express what should be changed and easiest to discuss. Please go ahead @williamd67.
