### ISSUE TITLE
Decide on a content and create new, "official" README file

### ISSUE THREAD

**Issue by civctp2** [civctp2/civctp2#3]

**Comment by civctp2** [comment]
@ptitSeb @LynxAbraxas 
Are you guys happy with current https://github.com/civctp2/civctp2/blob/9acd87c680c2/README.md file?
If yes, I think we can close this issue now. Agree?

**Comment by ptitSeb** [comment]
I'm ok with the Readme.

**Comment by civctp2** [comment]
cool! :) closing this one, then!
