### ISSUE TITLE
Music (ogg-files) not played on Linux

### ISSUE THREAD

**Issue by williamd67** [civctp2/civctp2#300]
The music files (ogg) are not played on Linux (at least not if you made all data-files lowercase). This is caused by the fact that on Linux the file-system is case-sensitive while on Windows it is case-insensitive.

Is it a correct assumption that all data-files should be lowercase on Linux as is suggested in README.md? 
>  If you find a strange behavior or think the files are not up-to-date, check that you don't have 2 copies of a file in different cases (lowercase everything if needed).

If so, this can be easily fixed by testing file-existence with lowercase. Currently there are still tests with capitals in the code.

**Comment by LynxAbraxas** [comment]
> If so, this can be easily fixed by testing file-existence with lowercase. Currently there are still tests with capitals in the code.

Have to check. This should not be the case since cifm (from @ptitSeb, introduced in e94c67a3bc786279270ad7c1b40686b7aecf2ce3 and ea5f1ecb84ac4faf223592cc64b61f3a3a7947e0) unless I missed something...

**Comment by williamd67** [comment]
FYI: the failing tests (3) for me are in soundmanager.cpp: `CI_FileExists("music/Track02.ogg")`

**Comment by LynxAbraxas** [comment]
Just checked: I used
```
mln -s 'Civilization - Call to Power - * - *' Track#1.ogg
```
so we could either change the default prefix string in the code or use `cifm` there as well.
All in all it would be great to refurnish the OGG playing also taking the issue of #34 into account.

**Comment by MartinGuehmann** [comment]
So what is the case the GOG files come with?

**Comment by williamd67** [comment]
I just checked: the.original files have the following casing ./ctp2_program/ctp/music/Track<xx>.ogg. In that case the code will work fine. I will re-install all the original GOG-files and check with master if it will work out-of-the-box.

**Comment by williamd67** [comment]
Checked with the latest master and ctp2 runs without changes of the file-/directory-names. So i closed the issue.
