### ISSUE TITLE
Incorrect unit-animations

### ISSUE THREAD

**Issue by williamd67** [civctp2/civctp2#307]
Sometimes unit animations start to jump forward and then continue their normal animation.

This is caused by the fact that the unit-animations are started from two different places (HandleNextAction) which sometimes invalidate the correct sequence.

**Comment by williamd67** [comment]
I found two other cases where the unit-animation shows some glitches. In both cases (boat and soldier) does an unit disappear (see images).
![boat-shown](https://user-images.githubusercontent.com/10560119/80620204-f8d05200-8a45-11ea-89e8-b474a6c59b7f.jpg)
![boat-hidden](https://user-images.githubusercontent.com/10560119/80620219-fec63300-8a45-11ea-9927-d1fe20146b27.jpg)
![soldier-shown](https://user-images.githubusercontent.com/10560119/80620239-0554aa80-8a46-11ea-9996-7d9b5c6a85e8.jpg)
![soldier-hidden](https://user-images.githubusercontent.com/10560119/80620249-084f9b00-8a46-11ea-908f-06c78643f1ff.jpg)

**Comment by williamd67** [comment]
I found out that during end-of-turn (when show enemy moves is enabled) there is a split in visual (UnitActor) and real (UnitData) position of the unit which are not aligned at that time. I assume that this causes the above mentioned glitches.

This may also cause the issue mentioned in #260 `Unit/army stays invisible even if in vision of stealth units` as the UnitData-position of those units is correct but the UnitActor-position is incorrect and the reason that they are not drawn.

I do not see an easy solution yet. 

Although I think the solution for the jumping unit is a good solution, together with the above described issue it has a side-effect that during some frames the unit is not rendered which causes a flicker (empty frame) during the unit animation. I propose not to merge this PR till the above mentioned issue has been solved as well.

**Comment by LynxAbraxas** [comment]
Hm, possibly this is even connected to #210, and that stealth units, which get revealed due to bumping into them, appear at the wrong position (I thought that we have an issue already for that but can't find it).

> I propose not to merge this PR till the above mentioned issue has been solved as well.

Just put WIP: in front of the subject/title, that is the convention to mark it that it is not yet ready for merge but open for discussion.

**Comment by LynxAbraxas** [comment]
> I found three other cases where the unit-animation shows some glitches. In two cases, a boat (see image 1 and 2) and a soldier (see image 3 and 4) does a unit disappear and in one case a unit appears: settler (see image 3 and 4).

What is causing the change between the states? Just time passing? If so what time difference was between the screen shots (ms, s or even min.)?

**Comment by williamd67** [comment]
I took the screenshots while the animation (show enemy moves is enabled) is shown. So the time between them is definitely shorter than a second.

You can reproduce this issue as I used the save file of #260 `dbgVisibility.zip` and enabled `show enemy moves' after end-turn (twice as there is a popup) you can see those effects.

**Comment by williamd67** [comment]
> What is causing the change between the states?

The GameEventManager moves all units into their new position and thereby updates the position of the UnitData. This is done before (or simultaneously) to the Director that moves the units on the screen and updates the UnitActor position. Now during the unit-animations the screen-renderer uses the UnitData-position to determine if a unit is visible, while the director uses the UnitActor-position to render the unit.

This is the main cause of the unit (dis)appearing:
1. the disappearing ship: its final position (UnitData) is off the screen so it does not need to be drawn; when it is its turn to be animated it will re-appear and be animated to its new position
2. the disappearing soldier: its final position (UnitData) is inside a transporter so it does not need to be drawn; again while it is moved to its position it is drawn by the directory; in this case there are two animations where in between the unit disappear from the screen;
3. the appearing settler: also here its final position (UnitData) is inside a transporter so it does not need to be drawn; etc.

To answer your other question when does the discrepancy between the two position happen: the UnitActor-position is not always updated, per example when a unit is part of an army but not the top-unit it will not be updated, when a unit is transported it will not be updated; this may causes side-effects that if the top-unit is killed or moved away that in some situations the visual (UnitActor) position is completely different than the position where the unit really is (UnitData).

**Comment by LynxAbraxas** [comment]
Thanks for posting your findings. I will have to digest those a bit before I can comment in more detail.

**Comment by williamd67** [comment]
This issue can be closed as it is fixed by #314.
