### ISSUE TITLE
double-free core dump

### ISSUE THREAD

**Issue by dsmouse** [civctp2/civctp2#309]
I just found this project.  WOW!  Thanks!
I tried to get it to run with GOG datam on FC11, got this after a few moves:

[mouse@apiary ctp]$ ./ctp2 --fullscreen
Detected Ogg Music track, using that instead of CD Audio
free(): double free detected in tcache 2
Aborted (core dumped)

I'm happy to explore if you can give me a few pointers as I'm new to this codebase!

**Comment by LynxAbraxas** [comment]
Welcome @dsmouse. Thanks. What commit did you choose for compilation? How did you compile?
One option would be to compile the debug-version or to run through a debugger like gdb or try catchsegv.

**Comment by MartinGuehmann** [comment]
This issue is stale. It could be related to better build instructions in #398. So, I guess we will never know what the solution is for this.
