### ISSUE TITLE
Binary packages for Linux

### ISSUE THREAD

**Issue by LynxAbraxas** [civctp2/civctp2#322]
Currently, all milestones for "Linux Release" are [solved](https://github.com/civctp2/civctp2/issues?q=milestone%3A%22Linux+Release%22+). The only thing that is missing I think is the creation of binary packages for Linux that could be used to install CTP2 with a package manager. This should be possible to do with the compilation done in CI. It would need some means to provide a path to the GOG/CD files that we cannot put in the package. Since the Dockerfile for CI uses Ubuntu for building, supporting only DEB-packages for a start seems reasonable. So all this needs is the automatic creation of a DEB-package as part of the CI to become CI-CD (continuous delivery). Since the smoke tests only work for GL, it would be good to use GL CI-CD, which would also offer the option for manual tests as a stage to continuous delivery.

**Comment by LynxAbraxas** [comment]
Just noticed that GL also offers free runners with tags `shared-windows` `windows` `windows-1809`, so it might even be possible to get CI-CD installs for windows builds with GL.
@MartinGuehmann what do you think? Should we go for GL CI-CD? As long as #285 is not resolved, this would only make sense if you are willing to push each merge to master manually to GL, or configure a push-event to GL on GH or locally.

**Comment by commel** [comment]
A lot of projects use [AppImages](https://appimage.org/) as nice way to distribute Linux binaries. They are selfcontained and easy to use with each new release.

Examples can be found at [OpenRA](https://www.openra.net/download/), [naev](https://naev.org/downloads/), [Julius](https://github.com/bvschaik/julius/releases) and so on.

**Comment by MartinGuehmann** [comment]
> Just noticed that GL also offers free runners with tags `shared-windows` `windows` `windows-1809`, so it might even be possible to get CI-CD installs for windows builds with GL. @MartinGuehmann what do you think? Should we go for GL CI-CD? As long as #285 is not resolved, this would only make sense if you are willing to push each merge to master manually to GL, or configure a push-event to GL on GH or locally.

In principle, automatic Windows builds are nice, but I would put these into their pull request then.
