### ISSUE TITLE
Getting advance from other civ or goody hut changes current researched advance

### ISSUE THREAD

**Issue by LynxAbraxas** [civctp2/civctp2#327]
If one gets an advance from other civ (steal, diplo, conquer city) or goody hut, the current researched advance is changed. This is not only annoying, but it can also happen that the limited list of advances available for research does not list the advance any more that was already under research. If that was the only one towards a specific goal, this is really annoying.

**Comment by williamd67** [comment]
Indeed, I had the same issue last week as well.

**Comment by LynxAbraxas** [comment]
I'd say that the general randomization of the advances that are listed for research (sub-set of max 4 advances that could be researched in regard to full-filled prerequisites) is fine, but the one already under research should be kept or at least always be part of the listing.

**Comment by LynxAbraxas** [comment]
Probably this code is related:
https://github.com/civctp2/civctp2/blob/4778e5cf0a0c18f55508088d76f7efdc52332293/ctp2_code/gs/gameobj/Player.cpp#L8047-L8065

**Comment by LynxAbraxas** [comment]
Solved with #339
