### ISSUE TITLE
Accepted diplomatic proposals seem to have no effect

### ISSUE THREAD

**Issue by LynxAbraxas** [civctp2/civctp2#33]
It seems that *diplomatic proposals* that get accepted seem to have no effect, in the master branch under linux. They work as expected in the linux branch. While this should not be related to the linux port, it would be great if someone could confirm that this probem does not exist under windows. This might be the actual cause for #29.
Rejections seem fine, at least a message about the rejection is presented in the *diplomatic proposals* window, while the window just closes when the proposel seems accepted. (I also noticed that the processing of computer players already continues before I close the proposal window, though it seems to wait until I hit "send", which suffices for proper logic processing.)

@DarkDust Do you think you could drop an email to the ctp2 code masters of old (like Martin Gühmann, ctplinuxfan, Maquiladora, Fromafar, richardh, J Bytheway) to point them at the new repos and the issue?

**Comment by LynxAbraxas** [comment]
Seems to be solved with #35, but even with #36 the diplomatic proposal window closes after clicking Send without waiting for a click on OK if the diplomatic proposal was initiated by an AI player. The agreement seem to be effective though. In a way the OK button only seems to serve as a "close window" button while the actual processing of agreements already happens when Send is clicked, still I find this behavior a bit irritating.

**Comment by LynxAbraxas** [comment]
It never happened to me with ctp2 on linux that an AI player offered to share advances, which happened a lot in ctp1. Has the AI lost the ability to do that or has it just become unlikely? Initiating and executing exchange of advances as a normal player does work though.

**Comment by MartinGuehmann** [comment]
@LynxAbraxas, I don't think that it has anything to with any recent or any code change at all. This is, I think, CTP2 out of the box behavior. As far as I can see in automatic AI testing, is that the AIs ask for map exchanges, pollution reduction, cease fire and piece treaties. (These things pop up even if the visible player is a robot.) That's all, and nothing has changed here.

Actually, this is to be expected since we have worked from little to nothing on diplomacy.

**Comment by LynxAbraxas** [comment]
Many thanks @DarkDust for the call!
