### ISSUE TITLE
Help with assembly code in C3Blitter Apple Silicon

### ISSUE THREAD

**Issue by whamtet** [civctp2/civctp2#361]
Sorry if this is a stupid question, but I'm having problems with the assembly code in c3blitter.cpp.  There are two sets of assembly to account for windows / linux, but nothing for ARM (Apple Silicon).  

Firstly, what is c3blitter for?  Second, do we still need to have assembly code here?  Aren't modern machines fast enough to just use regular cpp?

Any suggestions much appreciated.

**Comment by williamd67** [comment]
On Linux the assembly code is not used. In case you can ensure that the code between 57 and 78 of c3blitter.cpp is skipped (by #define or commented out), you can comment out all assembly code. I do not know if this will work for you.

**Comment by whamtet** [comment]
Thanks @williamd67 , I'm compiling on Linux actually so this is good to know.  But what about the second section?  L376 - 409?  Is that second function never invoked?

**Comment by whamtet** [comment]
Program seems to run fine with second section commented out, thanks for your suggestions @williamd67
