### ISSUE TITLE
How to enable console printing?

### ISSUE THREAD

**Issue by myocytebd** [civctp2/civctp2#393]
After SDL_Init(), printf/fprintf behavior changes. (e.g. may need fflush)
Some time later, printf/fprintf is fully broken.
How to bring them back?

**Comment by LynxAbraxas** [comment]
Not sure what you mean exactly. stdout is buffered (needs flush), stderr is not buffered. Did you try that?

**Comment by myocytebd** [comment]
stdout/stderr was totally broken, but I could not remember how to reproduce it or maybe due some package upgrade.
