### ISSUE TITLE
monthly rebuild GL-CI schedules 

### ISSUE THREAD

**Issue by LynxAbraxas** [civctp2/civctp2#396]
It would also be good especially with https://github.com/civctp2/civctp2/pull/385 to have monthly rebuild GL-CI schedules (https://gitlab.com/civctp2/civctp2/-/pipeline_schedules, see also e.g. https://github.com/civctp2/civctp2/pull/84#issuecomment-469378302 and https://github.com/civctp2/civctp2/pull/391#issuecomment-1364747099) to see if changes to the Ubuntu base image causes any problems.

**Comment by LynxAbraxas** [comment]
A monthly rebuild GL-CI schedule for https://gitlab.com/civctp2/ctp2CD/ would be good as well to avoid unexpected loss of the artifact for running the smoke tests.

**Comment by LynxAbraxas** [comment]
@MartinGuehmann all recent GL-CI pipelines failded due to https://github.com/civctp2/civctp2/pull/391#issuecomment-1365280202, i.e. the missing artifact from https://gitlab.com/civctp2/ctp2CD/.
Could you re-run the pipeline for master of https://gitlab.com/civctp2/ctp2CD/ (i.e. under the scheduels tab: https://gitlab.com/civctp2/ctp2CD/-/pipeline_schedules) which should rebuild the artifact. 
You could also give me higher rights on GL on both projects, then I could manage that and other GL related settings like e.g. #397.

**Comment by MartinGuehmann** [comment]
I rebuilt the artifact and rerun the tests on the latest merge. The merge passed the tests. I also promoted you to maintainer in both GitLab projects.

**Comment by LynxAbraxas** [comment]
Many thanks, @MartinGuehmann! Looks great and I was able to also create a monthly build schedule for civctp2 master in order to check if changes to the base DI (currently ubuntu:latest, which points to the "latest LTS" (https://hub.docker.com/_/ubuntu) so currently latest is 22.04 (jammy)).
