### ISSUE TITLE
Non-Win Debug Builds

### ISSUE THREAD

**Issue by jacobgruber** [civctp2/civctp2#407]
I'd like to enable the DEBUG flag for my linux and experimental macos builds, but afaict, this seems to draw in windows specific code in a lot of places. Has anyone used this flag outside of windows?

**Comment by MartinGuehmann** [comment]
Yes, if you check the instructions, whether in the current readme or in #406. It tells you how to build it. In fact, I made it working. I just can't tell you whether it is working on a Mac. That's something you have to find out yourself.

**Comment by LynxAbraxas** [comment]
There is also a debug build in GL-CI with the BTYP arg to the docker build:
https://github.com/civctp2/civctp2/blob/67532c1338ad8c0f8e943a6e04633782543fa06a/.gitlab-ci.yml#L39
https://github.com/civctp2/civctp2/blob/9cd7c309e13e93d86c42377db078980e16cefd4c/Dockerfile#L37-L43
