### ISSUE TITLE
AVCodecContext error when building on Debian12

### ISSUE THREAD

**Issue by rambo919** [civctp2/civctp2#412]
> ui/aui_sdl/aui_sdlmovie.cpp: In function ‘int stream_component_open(VideoState*, int)’:
> ui/aui_sdl/aui_sdlmovie.cpp:1581:9: error: ‘AVCodecContext’ was not declared in this scope; did you mean ‘AVIODirContext’?
>  1581 |         AVCodecContext *avctx;
>       |         ^~~~~~~~~~~~~~
>       |         AVIODirContext
> ui/aui_sdl/aui_sdlmovie.cpp:1581:25: error: ‘avctx’ was not declared in this scope
>  1581 |         AVCodecContext *avctx;
>       |                         ^~~~~
> ui/aui_sdl/aui_sdlmovie.cpp:1589:46: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
>  1589 |         if (stream_index < 0 || stream_index >= ic->nb_streams)
>       |                                 ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
> ui/aui_sdl/aui_sdlmovie.cpp:1592:17: error: ‘avcodec_alloc_context3’ was not declared in this scope; did you mean ‘avio_alloc_context’?
>  1592 |         avctx = avcodec_alloc_context3(NULL);
>       |                 ^~~~~~~~~~~~~~~~~~~~~~
>       |                 avio_alloc_context
> ui/aui_sdl/aui_sdlmovie.cpp:1596:15: error: ‘avcodec_parameters_to_context’ was not declared in this scope; did you mean ‘avcodec_parameters_copy’?
>  1596 |         ret = avcodec_parameters_to_context(avctx, ic->streams[stream_index]->codecpar);
>       |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>       |               avcodec_parameters_copy
> ui/aui_sdl/aui_sdlmovie.cpp:1599:9: error: ‘av_codec_set_pkt_timebase’ was not declared in this scope
>  1599 |         av_codec_set_pkt_timebase(avctx, ic->streams[stream_index]->time_base);
>       |         ^~~~~~~~~~~~~~~~~~~~~~~~~
> ui/aui_sdl/aui_sdlmovie.cpp:1616:20: error: ‘avcodec_open2’ was not declared in this scope; did you mean ‘avio_open2’?
>  1616 |         if ((ret = avcodec_open2(avctx, codec, NULL)) < 0) {
>       |                    ^~~~~~~~~~~~~
>       |                    avio_open2
> ui/aui_sdl/aui_sdlmovie.cpp:1670:9: error: ‘avcodec_free_context’ was not declared in this scope; did you mean ‘avformat_free_context’?
>  1670 |         avcodec_free_context(&avctx);
>       |         ^~~~~~~~~~~~~~~~~~~~
>       |         avformat_free_context
> ui/aui_sdl/aui_sdlmovie.cpp: In function ‘int stream_has_enough_packets(AVStream*, int, PacketQueue*)’:
> ui/aui_sdl/aui_sdlmovie.cpp:1687:51: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
>  1687 |                    queue->nb_packets > MIN_FRAMES && (!queue->duration || av_q2d(st->time_base) * queue->duration > 1.0);
>       |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ui/aui_sdl/aui_sdlmovie.cpp: In function ‘int is_realtime(AVFormatContext*)’:
> ui/aui_sdl/aui_sdlmovie.cpp:1698:37: error: ‘AVFormatContext’ {aka ‘struct AVFormatContext’} has no member named ‘filename’
>  1698 |         if(s->pb && (   !strncmp(s->filename, "rtp:", 4)
>       |                                     ^~~~~~~~
> ui/aui_sdl/aui_sdlmovie.cpp:1699:56: error: ‘AVFormatContext’ {aka ‘struct AVFormatContext’} has no member named ‘filename’
>  1699 |                                         || !strncmp(s->filename, "udp:", 4)
>       |                                                        ^~~~~~~~
> ui/aui_sdl/aui_sdlmovie.cpp: In member function ‘virtual AUI_ERRCODE aui_SDLMovie::Open(uint32, aui_Surface*, RECT*)’:
> ui/aui_sdl/aui_sdlmovie.cpp:2015:23: warning: ‘void av_init_packet(AVPacket*)’ is deprecated [-Wdeprecated-declarations]
>  2015 |         av_init_packet(&flush_pkt);
>       |         ~~~~~~~~~~~~~~^~~~~~~~~~~~
> /usr/include/x86_64-linux-gnu/libavcodec/packet.h:512:6: note: declared here
>   512 | void av_init_packet(AVPacket *pkt);
>       |      ^~~~~~~~~~~~~~
> ui/aui_sdl/aui_sdlmovie.cpp: In member function ‘virtual AUI_ERRCODE aui_SDLMovie::Resume()’:
> ui/aui_sdl/aui_sdlmovie.cpp:2102:1: warning: no return statement in function returning non-void [-Wreturn-type]
>  2102 | }
>       | ^
> ui/aui_sdl/aui_sdlmovie.cpp: In member function ‘virtual AUI_ERRCODE aui_SDLMovie::Process()’:
> ui/aui_sdl/aui_sdlmovie.cpp:2119:1: warning: no return statement in function returning non-void [-Wreturn-type]
>  2119 | }
>       | ^
> ui/aui_sdl/aui_sdlmovie.cpp: In member function ‘bool aui_SDLMovie::HandleMovieEvent(SDL_Event&)’:
> ui/aui_sdl/aui_sdlmovie.cpp:2168:75: warning: suggest parentheses around comparison in operand of ‘&’ [-Wparentheses]
>  2168 |                                 if ((event.motion.type & SDL_BUTTON_LMASK != 0) &&
> ui/aui_sdl/aui_sdlmovie.cpp: At global scope:
> ui/aui_sdl/aui_sdlmovie.cpp:1029:13: warning: ‘void step_to_next_frame(VideoState*)’ defined but not used [-Wunused-function]
>  1029 | static void step_to_next_frame(VideoState *is)
>       |             ^~~~~~~~~~~~~~~~~~
> ui/aui_sdl/aui_sdlmovie.cpp:417:13: warning: ‘void decoder_init(Decoder*, int*, PacketQueue*, SDL_cond*)’ defined but not used [-Wunused-function]
>   417 | static void decoder_init(Decoder *d, AVCodecContext *avctx, PacketQueue *queue, SDL_cond *empty_queue_cond) {
>       |             ^~~~~~~~~~~~
> make[2]: *** [Makefile:3718: ui/aui_sdl/aui_sdlmovie.o] Error 1
> make[2]: Leaving directory '/media/rambo919/Data/Inc/civctp2-master/ctp2_code'
> make[1]: *** [Makefile:3755: all-recursive] Error 1
> make[1]: Leaving directory '/media/rambo919/Data/Inc/civctp2-master/ctp2_code'
> make: *** [GNUmakefile:471: all-recursive] Error 1

**Comment by LynxAbraxas** [comment]
@rambo919 you can try with the commits of #413.

**Comment by rambo919** [comment]
> @rambo919 you can try with the commits of #413.

Was a bit of a PITA to figure that out (especially since I did not at first notice it was a fork) due to github newb errors on my end.

Compiles and runs fine.

**Comment by MartinGuehmann** [comment]
#413 has been merged. So closing this.
