### ISSUE TITLE
Set up travis-ci for Linux builds

### ISSUE THREAD

**Issue by DEVoytas** [civctp2/civctp2#5]

**Comment by LynxAbraxas** [comment]
Basically readily configured by @ptitSeb commits like [071f8533e201bff969](https://github.com/civctp2/civctp2/commit/071f8533e201bff9693b0f6c6ed92e36da495a91).

**Comment by civctp2** [comment]
@LynxAbraxas yes but apart from local setup, I think you need to setup travis  service account for the project.
Since @ptitSeb has already done it for his project, he obviously knows how to do it.
But I think to do it, he needs to provide project credentials to the travis-ci service, is that correct @ptitSeb ?

**Comment by ptitSeb** [comment]
Yes, you need to create an account on travis and link it to the account on github, plus allow  on github the travis service to interact (and it's the same for appveyor). After that, in travis you enable the build for the repo and you put your `.travis.yml` file (it's already there) and setup the nice and shiny badge on the README.md

Once setup, travis will also check that each PR doesn't break the build, and that's nice!

**Comment by DEVoytas** [comment]
> and it's the same for appveyor

Yes, but before that we will need to figure out windows builds first. My understanding is that they are not working at the moment, right?

> Once setup, travis will also check that each PR doesn't break the build, and that's nice!

Yes, I agree, that is really nice feature! I was going to ask, whether it only builds master (so you only know something is wrong after the fact, i.e. when it's already merged) or whether it can verify PRs so you can know in advance. Good to know it can! :)

@ptitSeb could you take care about that ? If yes, we will need to find a way to securely provide you with account credentials... Any ideas?

**Comment by ptitSeb** [comment]
It would be much easier for the actual maintainer to create and links account. Let's have a maintainer first, then setup the travis account.

**Comment by DEVoytas** [comment]
Oh, my understanding was that you already agreed to be a maintainer but I guess I forgot (or maybe rather [repressed](https://en.wikipedia.org/wiki/Repression_(psychology)) :-) ), that it was conditional agreement and that you can only start from November.

In that case could you estimate how long you think it would take for someone who has never done it, to create travis account and set-up everything?
If this is not too much time, maybe I could try to do it myself...

**Comment by ptitSeb** [comment]
I think it should take around 10 min if you have access to the github repo... It really is a piece of cake to setup.

**Comment by DEVoytas** [comment]
OK, guys. This is done now: https://travis-ci.com/civctp2/civctp2

[![Build Status](https://travis-ci.com/civctp2/civctp2.svg?branch=master)](https://travis-ci.com/civctp2/civctp2)  :)

So closing it.
