### ISSUE TITLE
Trade routes visible even in fog of war

### ISSUE THREAD

**Issue by LynxAbraxas** [civctp2/civctp2#50]
Trade routes are visible even in fog of war, which gives city positions away of cities that are not know to the player otherwise. It would be great if trade routes would only be visible outside "fog of war", such that their full path especially start and end is not obvious and motivate discovery expeditions.

**Comment by MartinGuehmann** [comment]
I guess that can also be closed.

**Comment by LynxAbraxas** [comment]
Yes, deprecated with #256.
