### ISSUE TITLE
Wrong city name for messages like "slaves put at work at ..."

### ISSUE THREAD

**Issue by LynxAbraxas** [civctp2/civctp2#51]
Somtimes the names of cities in messages e.g.  "slaves put at work at ..." are wrong (but not always).

**Comment by MartinGuehmann** [comment]
I guess, you added some strings and loaded an old savegame?

**Comment by LynxAbraxas** [comment]
Thank @MartinGuehmann for taking a look at this issue.

> I guess, you added some strings and loaded an old savegame?

No, this even happens in a "vanilla" game, and only sometimes the city names are wrong, not always. 
If I add some strings concerning the game messages or the goods, I get completely different message strings like "citizen starving" instead of "building X was finished".

**Comment by MartinGuehmann** [comment]
I guess then we need it a little bit more specific and also a savegame right before that happens.

Probably, for the slaves you could just put slaves onto the map and then see were the slaves go.

**Comment by LynxAbraxas** [comment]
Hm, how do you place slaves onto the map? Is ther some kind of slave unit?

**Comment by MartinGuehmann** [comment]
> Hm, how do you place slaves onto the map? Is ther some kind of slave unit?

That's supposed to be slavers. One "r" missing.

**Comment by LynxAbraxas** [comment]
Had a look for possible sources of this issue but could not find any but so far. The point where the city goes into the message is here:
https://github.com/civctp2/civctp2/blob/9a1ab16704ccb10c23d14a679adff21501fcd910/ctp2_code/gs/gameobj/ArmyData.cpp#L3057
Possibly the lookup of the city name for the message string is buggy.

**Comment by LynxAbraxas** [comment]
Observing something similar in the case of franchise removal with #191, e.g. I'm told franchise in Sligo closed but the city icon indicates the franchise was removed in Cork:

![ss_2019-10-03_22:01:05](https://user-images.githubusercontent.com/21012234/66162166-1b27fb80-e62e-11e9-8f72-92851d3153c3.png)

If I go  there with a unit, it actually was Cork and not Sligo:

![ss_2019-10-03_22:02:22](https://user-images.githubusercontent.com/21012234/66162304-63471e00-e62e-11e9-9ec2-22f87aace33f.png)

Similar here with Rivas and Makale:

![ss_2019-10-03_22:16:50](https://user-images.githubusercontent.com/21012234/66162337-73f79400-e62e-11e9-9b84-4a74def78857.png)

Both this message and that of slave raids ends up here:
https://github.com/civctp2/civctp2/blob/490cce638e0681d7053b2285c6de955fea3a49dc/ctp2_code/gs/world/Cell.cpp#L879-L889
Possibly there is something wrong with `SetCity`:
https://github.com/civctp2/civctp2/blob/490cce638e0681d7053b2285c6de955fea3a49dc/ctp2_code/gs/world/Cell.cpp#L869-L877
@MartinGuehmann any idea?

**Comment by MartinGuehmann** [comment]
> @MartinGuehmann any idea?

Not really, superficially the code looks OK. The code uses the actual position of the city, so that should be fine. But still somehow it mixes up the cities. If it are always adjacent cities then it could be that the AI moves from one city to the other and tries to sue both.

Anyway, if you wanna check this you need to use the logs of the debug version.

**Comment by LynxAbraxas** [comment]
Issue resolved in the case of franchise removal, see: https://github.com/civctp2/civctp2/pull/191#issuecomment-538770514

**Comment by LynxAbraxas** [comment]
Solved for enslaving settlers with #199.
