### ISSUE TITLE
Linux version loads save games created on Windows and creates save games that load on Windows

### ISSUE THREAD

**Issue by MartinGuehmann** [civctp2/civctp2#55]
Now, the Linux version creates and loads save games that are created on Windows. Unfortunately, this breaks save games you created while testing.

This is an issue with binary compatibility. Since these save games you created are unofficial, they won't be supported, unless you go into the hassle to do it yourself.

To do so I had to implement the struct GUID, which has to be 16 byte big. _MAX_PATH has to be 260, as on Windows. Activision did something with it that is not good. Maybe it has some unwanted side effects. But we will see.

**Comment by LynxAbraxas** [comment]
The compatibility between OSs is great (though I do miss my late save game...). How about a save game file in the repos (commit on separate branch for a PR for testing first) as a standard for testing loading on linux and win?
Would saving the loaded game lead to a bit-exact result again that could be compared to the standard by a checksum or would there be time-stamps or random seeds in it that would change?

**Comment by MartinGuehmann** [comment]
> How about a save game file in the repos (commit on separate branch for a PR for testing first) as a standard for testing loading on linux and win?

Sure, I already thought about having one in it. I would donate my test game. It is a game from 4000 BCE, which I usually load and run for 200 or 400 turns. Lately, I also did for 800 turns. These AIs like Trumpy Bumpy: Global warming is bull****. I agree raising sea levels and deserted land really sucks. And still these AIs don't get, let's have our spies planting A-bombs everywhere, yeah.

The question is were to put. I use Activision's developer setup, which creates the executable ..\ctp2_code\ctp\ on Windows and that is also the working directory. The save games are stored in a subdirectory. That is by the way the reason for the Run.sh, but I think I don't need it anymore. On Linux you have other possibilities, especially if you want to use the home directory. And actually, storing save games in the exe directory or a subdirectory isn't standard in Windows 10 either, that is Win95/Win98.

Then what would be the name of such a directory, I already have a directory among my savegames called Test, so maybe DevTest.

> Would saving the loaded game lead to a bit-exact result again that could be compared to the standard by a checksum or would there be time-stamps or random seeds in it that would change?

I am not sure, whether I understand the question. Obviously, you get an error that something is wrong with the save game. They have some magic numbers, at least they call it magic numbers.

Maybe, I got it now.: You mean if I load a save game and then save it without doing anything else, that the save files should be identical. I think the size will be identical, since this depends just on the number of objects in the game, e.g players, units, or cities. What the game could do on load is to update or recalculate values, which may change things. And on a load I noticed that it would center on the active unit, even so it shouldn't do it. Or it would activate that unit. And if it saves the selected item then of course this changes.

And you added some goods to the database, which is in principle an incompatibility. It invalidates existing trade routes. In the load turn you see that all the trade routes are about rubies. The AIs just cancel these routes and create new ones. So it is a minor incompatibility. Fromafar, tried to fix this, but it does not work under all circumstances. When I made GoodMod, I wasn't aware of this either, I just saw that I could load the game and continue, and that was it.

So if you ask for test, then I would just say passed if the game loads.

**Comment by LynxAbraxas** [comment]
> The question is were to put. 

According to the install instructions I copy `ctp2_data/` over to the install dir:
https://github.com/LynxAbraxas/ctp2DF/blob/master/Dockerfile#L75
so why not put it in a subfolder `DevTest` there in `ctp2_data/`?

> You mean if I load a save game and then save it without doing anything else, that the save files should be identical.

Yes, that is what I meant, but if that is unsure, let's just go for a `load-game` test that passes if the loading is successful and a `save-game` test that succeeds if a file of non-zero size is the result. This could be extended with a following load-test of that save-game.
I can only help with setting up automated smoke-testing on GL and Sikuli like https://github.com/LynxAbraxas/ctp2DF/ does. Travis seems to be similar in quite a few aspects.

**Comment by MartinGuehmann** [comment]
> > The question is were to put.
> 
> According to the install instructions I copy `ctp2_data/` over to the install dir:
> https://github.com/LynxAbraxas/ctp2DF/blob/master/Dockerfile#L75
> so why not put it in a subfolder `DevTest` there in `ctp2_data/`?

If you wanna test it automatically then it would be in a subfolder of:

/media/martin/76A08F11A08ED6D1/Activision/CivCTP2/ctp2_program/ctp/save/games/
/media/martin/76A08F11A08ED6D1/Activision/CivCTP2/ctp2_code/ctp/save/games/

That is my Windows 10 Drive C mounted into my Kubuntu file system. ctp2_program/ctp is the directory of ctp2.exe in the released version of CTP2. Just note that ctp2_program contains only the ctp directory, which for an end user does not make any sense. However, ctp2_program is a stripped down version of ctp2_code, on Windows ctp2.exe is build in ctp2_code\ctp\ and also run from there if you start it from Visual Studio. In principal we could put it into /ctp2_code/ctp/save/games/ and you can copy it for testing where ever need it.

> Yes, that is what I meant, but if that is unsure, let's just go for a `load-game` test that passes if the loading is successful and a `save-game` test that succeeds if a file of non-zero size is the result. This could be extended with a following load-test of that save-game.

I would go for the save game load, save, and reload. You can have many reasons for a save game that is non-zero in size, most of them mean the file is corrupt in one or another way and only one means it is OK.

> I can only help with setting up automated smoke-testing on GL and Sikuli like https://github.com/LynxAbraxas/ctp2DF/ does. Travis seems to be similar in quite a few aspects.

I guess that is more than nothing. Ideally, we would like to have this for an upload test.

**Comment by LynxAbraxas** [comment]
> ctp2_code/ctp/save/games/ and you can copy it for testing where ever need it.

That seems reasonable.

> Ideally, we would like to have this for an upload test.

It already is. If you clone/push https://github.com/LynxAbraxas/ctp2DF/ to GitLab, create a private ctp2CD repos there with the necessary game files (see my corresponding GL repos) and change the ctp2/ submod URL to https://github.com/civctp2/civctp2/ GL will run all jobs including tests defined in https://github.com/LynxAbraxas/ctp2DF/blob/master/.gitlab-ci.yml whenever new commits are pushed to that GL ctp2DF repos. 
The setup of ctp2DF can be transferred to be part of civctp2 directly. If GL is set up to mirror the GH repos it will test new commits to https://github.com/civctp2/civctp2/ automatically, similar to travis now but due to the private repos option, the test can cover not only building but also the game play with smoke-tests based on sikuli, and you end up with a docker image ready for playing.

**Comment by MartinGuehmann** [comment]
That wold be good to have.

**Comment by LynxAbraxas** [comment]
> That wold be good to have.

Opened new issue for this topic: #68

**Comment by LynxAbraxas** [comment]
@MartinGuehmann Does commit https://github.com/civctp2/civctp2/commit/22dd180480445561bbbcd3efc60f08d2fe5c53e5 only have changes for the save-file compatibility or are there any other changes in it?
I.e. to continue with my current game (due to the adiction of working on the code of ctp2 I never ever have finished a ctp2 game...) could I use current master, revert https://github.com/civctp2/civctp2/commit/22dd180480445561bbbcd3efc60f08d2fe5c53e5  to end up with a ctp2 version with all new features from master except the game compatibility for my ctp2DF.
Would https://github.com/civctp2/civctp2/commit/22dd180480445561bbbcd3efc60f08d2fe5c53e5 be the only one I would have to revert?

**Comment by MartinGuehmann** [comment]
There is another change for the configure.ac, so that you can configure a version that writes an extended log. However, I did not test it. And it shouldn't affect your build anyway.

And in c3.h you have a change from an earlier commit. Just find in there _MAX_PATH, and revert it to the original, which is still there as a comment. Actually, the save game converter isn't so difficult if you just want to have to work. You just have to revert the load code, and keep the save code. Then you can load and save games as long as the Load Window does not crash. Then you have to empty the save game folder of converted games.

Unfortunately, I wanted to get rid of the stuff I have in my work copy first. But for that you just need to modify GameFile.cpp. Here you have especially care about the _MAX_PATH, so that it is on the load side whatever comes from your OS and on the save side 260

**Comment by LynxAbraxas** [comment]
@MartinGuehmann It's very confusing to me here what goes where in which commits. Could you create a new branch for a PR in which you revert what is needed from https://github.com/civctp2/civctp2/commit/22dd180480445561bbbcd3efc60f08d2fe5c53e5 and other commits such as the `c3.h` `_MAX_PATH` code and create two following commits, first one (call it XYZ) that only changes the saving (keeping the loading unchanged) and then in the following commit the loading of the new save-games?
That way there would be an easy way for others to compile a ctp2 version at XYZ that loads the old games and saves them in the new format that can then be used for the game compiled with commits following XYZ.
I'm happy to test the three commits of that PR before it is merged;-)

**Comment by MartinGuehmann** [comment]
OK, I uploaded the pull request, however for now only load and save are reverted. I still have to think about the GUID.

I did not test it whether it builds or whether it indeed undoes the change.

**Comment by LynxAbraxas** [comment]
Can be closed with #77 merged in.

**Comment by MartinGuehmann** [comment]
We still could update the readme of master to mention. Then we should have everything.

**Comment by LynxAbraxas** [comment]
Concerning the README.md there is https://github.com/civctp2/civctp2/pull/77/commits/abe012820f983ca65ce4da54ab3c532fdf546c78.

**Comment by MartinGuehmann** [comment]
Yeah, I just have to cherry pick it.

**Comment by LynxAbraxas** [comment]
Ah, sorry, wasn't aware that https://github.com/civctp2/civctp2/commit/abe012820f983ca65ce4da54ab3c532fdf546c78 did not go into master despite the merge.

**Comment by MartinGuehmann** [comment]
Opened pull request #86, so that the updated readme can also go into master. This means all tasks of this issue are done, including informing people, when #86 is in (after the checks). But I think we can already close this.
