### ISSUE TITLE
Commit f228215 broke the build

### ISSUE THREAD

**Issue by DEVoytas** [civctp2/civctp2#57]
From the build history: https://travis-ci.com/civctp2/civctp2/builds it looks like commit https://github.com/civctp2/civctp2/commit/f22821505d20ff5bbb698dc3db9828c145b53f1e is the one that broke the build: https://travis-ci.com/civctp2/civctp2/builds/97939556

Build logs:
- https://travis-ci.com/civctp2/civctp2/jobs/171647537
- https://travis-ci.com/civctp2/civctp2/jobs/171647538

@MartinGuehmann, I think that the reason it went unnoticed is because the commits were pushed directly to master branch. The better workflow is to create the pull requests that are verified by travis-ci and only merge them to master branch when they pass all the checks.
Alternatively, if one does want to push commits directly rather than creating  PRs 
for every single commit, it's better to have dedicated branch for this (maybe 'dev'), that is also verified by travis-ci, and only merge it back to master when it's in known good state.
Other workflows are also possible but I think the main goal should be to keep master in known healthy state, that can be always trusted to produce good binary.

**Comment by MartinGuehmann** [comment]
Of course master should be kept in a healthy state. Looks like a beginner mistake. But it shows a problem with the freetype library: Currently, if I clean the project the freetype library is not cleaned. So without a fresh install I couldn't have caught it. The other problem, I could have caught if I had build it on Linux. Of course, this shows that travis-ci can check whether it builds on Linux, but so far it can check Windows builds, which is also be needed. It is quite a pain in the ass to keep the thing compiling on all platforms, even if you can access them.

Ideally, I would like to have something like: Push to whatever designated branch. Check whether it builds, if yes push to master, automatically. That would minimize bureaucracy as much as possible. Well, I haven't tried so far but would a pull request open again if something new is pushed to that branch?

**Comment by DEVoytas** [comment]
There already is the issue for setting up Windows automatic checks: https://github.com/civctp2/civctp2/issues/6.
One issue with merging to master automatically is, that it does not allow you to have any review or discussion on incoming changes.

**Comment by MartinGuehmann** [comment]
Thanks for pointing that out. Since, having these many issues here, and I think it is still a moderate number,  it is hard to catch them all. And especially, what is in, exactly.

If it is just about discussing and reviewing the changes, would it be fine to have it after merge? I can wait for  a few days, but on the other hand I don't wanna wait for eternity. And the more pull requests I have things may get more difficult to merge. So I would rather merge than not merge and sort out problems later. Some problems may even show up long after that.

If you think that has disadvantages I would like to hear them, and also if you don't see any disadvantages, at least right now.

**Comment by LynxAbraxas** [comment]
Not sure about what would be an appropriate waiting time. Best would be to have an automated windows test #6 as well and then at least only merge if all test succeed. Otherwise, two weekends might be appropriate to wait for comments if no discussion has gone on.

**Comment by MartinGuehmann** [comment]
Then I guess that was too soon: #63 
But #59 should have been right since it just adds a stub, which is of course open for future addition.
#58 and #61 should have been right, because they fix immediate needs.

**Comment by MartinGuehmann** [comment]
WIP means in English work in progress, ack. Children just ask if they don't understand something, adults just ignore and try to understand what is left. And left was the pull request. The request to put you stuff into master. That is what I just did. Sorry for that.

I think I have never seen the acronym WIP before. And I only have heard people saying "work in progress", for sure not double-you-eye-pea, that would be have four syllables like the original. So it doesn't save any breath, just removes the meaning. I looked it up in a dictionary. There is a chance to find it. But it seems not be so popular that any native speaker has to know it. It is a bit hard to decide whether I have to know it. But for sure I did not.

**Comment by LynxAbraxas** [comment]
No problem;-) had to learn that too, but it is quite common, see e.g.:
https://github.com/marketplace/wip

I think in general you cannot expect feedback unless you give two weekends time as this is quite likely a hobby project to others.

**Comment by DEVoytas** [comment]
@MartinGuehmann, @LynxAbraxas  Since master builds and passes all checks now, perhaps this issue should be closed, and new issue for discussing workflows should be opened?
I think It would be easier to follow and later find the discussion if it's subject corresponds to what is being discussed.

**Comment by MartinGuehmann** [comment]
Let's do as suggested by @DEVoytas, and continue in #65.
