### ISSUE TITLE
Automated upload testing (CI)

### ISSUE THREAD

**Issue by LynxAbraxas** [civctp2/civctp2#68]
New issue for side discussion of https://github.com/civctp2/civctp2/issues/55#issuecomment-457782867

 >   Ideally, we would like to have this for an upload test.

It already is. If you clone/push https://github.com/LynxAbraxas/ctp2DF/ to GitLab, create a private ctp2CD repos there with the necessary game files (see my corresponding GL repos) and change the ctp2/ submod URL to https://github.com/civctp2/civctp2/ GL will run all jobs including tests defined in https://github.com/LynxAbraxas/ctp2DF/blob/master/.gitlab-ci.yml whenever new commits are pushed to that GL ctp2DF repos.
The setup of ctp2DF can be transferred to be part of civctp2 directly. If GL is set up to mirror the GH repos it will test new commits to https://github.com/civctp2/civctp2/ automatically, similar to travis now but due to the private repos option, the test can cover not only building but also the game play with smoke-tests based on sikuli, and you end up with a docker image ready for playing.

**Comment by LynxAbraxas** [comment]
This would be an extended version of #13, i.e. attaching  https://github.com/LynxAbraxas/ctp2DF/  to https://github.com/civctp2/civctp2/ (squashed, if wanted), and would need some way to exclude the use of ctp2CD for travis docker build or we would need to remove the docker build test on travis such that the docker build test is only run by GL.
A nice side-effect of these tests are automatic screen shots of the game in various states, created for each pipeline. It would even be possible to record a video of some rounds played only by the AI.

**Comment by MartinGuehmann** [comment]
@LynxAbraxas, ideally I would like to leave this to you. In principle, I could add you as a collaborator to the project. Would you be fine with that?

**Comment by LynxAbraxas** [comment]
> In principle, I could add you as a collaborator to the project. Would you be fine with that?

Thanks for that special offer, I feel very honoured, but currently I would decline, because I want to avoid getting into CTP2-coding addiction again... My new years resolution was to stay away for at least a year (very successful yet, as you can see...). I only ended up active here again because of the recent new activity since you became maintainer and I wanted to help out on the open PRs of mine.

Since these GL-CI changes for smoke-testing would not concern GH but GL, adding me as a collaborator to GH wouldn't help anyway. 
I am inclined to help with this testing side-project but would want to know if the direction of #13 would be one that would in general be accepted, otherwise it would be too much work for nothing.

**Comment by MartinGuehmann** [comment]
Well, I don't have experience with such testing side-projects. That means I have no strong opinion about. And so, I cannot really judge the pros and cons about it. For some reason you concluded that it wasn't was to include at least at that time.

This means it would also require some time from my side to set it up, properly. Maybe @DEVoytas can still add something.

**Comment by LynxAbraxas** [comment]
I investigated a bit how to pass the CD data needed for running ctp2 for the smoke-tests without using a private submodule. It might be possible to pass the data as an artifact from another project/repo https://gitlab.com/gitlab-org/gitlab-ce/issues/14728#note_23441832. That way a submodule dependency could be avoided. If that were taken care of, would the general ideas and tests of ctp2DF  and the dep. on GL be accepted?

**Comment by LynxAbraxas** [comment]
Created #84 in regard to this issue.

**Comment by LynxAbraxas** [comment]
Closed, now that #84 is in and functioning.
