### ISSUE TITLE
SDL_ffmpeg for videos

### ISSUE THREAD

**Issue by MartinGuehmann** [civctp2/civctp2#88]
Currently, we are using SDL_ffmpeg for videos. However, right now it an old version and it is not developed actively anymore.  We have in pull request #62 some discussion about.

Probably, we need to update the code of SDL_ffmpeg and its use in CTP2 anyway. An alternative could be SDL since it has a header about videos.

**Comment by LynxAbraxas** [comment]
>   Yes, I had updated SDL_ffmpeg for ctp2!

@ptitSeb Did you finish? Do you have any instructions on using/compiling your version? What version of ffmpeg does it build on?

I would then try to use it with the instruction to continue on https://github.com/LynxAbraxas/ctp2DF/commits/videos4master for automated testing.

**Comment by ptitSeb** [comment]
Yes, I finished. But it still use some "deprecated" function, so maybe it isn't working anymore with current ffmpeg version.
It's been more than a year ago, so I may have forgoten things.
There is nothing spectacular for the build, it's a regular cmake project, so create a `build` folder, use `cmake` (or `ccmake` to check it founds all `avXXXX` libs) then make and that's it.

**Comment by LynxAbraxas** [comment]
Thanks @ptitSeb. So was it working with the ffmpeg version that was current when you finished? It took me a lot of time finding out the compatible version of ffmpeg for the old SDL_ffmpeg that ctp2 was originally using.
Did you check if your updated version of SDL_ffmpeg was compatible with the way it is called/used by ctp2? I had the impression, that ctp2 would need adjustments even for the last release of @arjanhouben.

**Comment by ptitSeb** [comment]
Yes, SDL_ffmpeg was compatible with current version (last year), but I haven't tried with current current version.
Also, I hadn't started really pluggin that version in CTP2, so I cannot say if it needs adjustments or not.

**Comment by LynxAbraxas** [comment]
It is even difficult to find out what was the current version of ffmpeg at the time of your last commit (https://github.com/ptitSeb/SDL_ffmpeg/commit/32767d4e223090396995aae84730331bf1d39cfb). @ptitSeb would you have a look at:  https://ffmpeg.org/olddownload.html https://ffmpeg.org/download.html and https://github.com/FFmpeg/FFmpeg/releases?after=n3.0.11 and check what version of ffmpeg you used?

**Comment by MartinGuehmann** [comment]
I guess this can now be closed.

**Comment by LynxAbraxas** [comment]
Yes, deprecated with #298.
