### ISSUE TITLE
odd AI behaviour when encountering other player's stealth units

### ISSUE THREAD

**Issue by LynxAbraxas** [civctp2/civctp2#91]
The AI always seems to attack other player's stealth units when encountered within its own borders without taking diplomatic actions and state into account. I often experienced that with e.g. clerics, the AI attacks (breaks standing peace contracts) and just in the following round the AI wanted to agree on peace again.

**Comment by MartinGuehmann** [comment]
I assume this is addressed by commit 412aa81 in pull request #101. Looks like this is not only about stealth units but about any units.

**Comment by LynxAbraxas** [comment]
Seems to be resolved with #101, this issue should be closed when #101 is merged.

**Comment by LynxAbraxas** [comment]
@MartinGuehmann, possibly only resolved for clerics (see #224)?
